export default {
  "login": "pramit-marattha",
  "id": 37651620,
  "node_id": "MDQ6VXNlcjM3NjUxNjIw",
  "avatar_url": "https://avatars0.githubusercontent.com/u/37651620?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/pramit-marattha",
  "html_url": "https://github.com/pramit-marattha",
  "followers_url": "https://api.github.com/users/pramit-marattha/followers",
  "following_url": "https://api.github.com/users/pramit-marattha/following{/other_user}",
  "gists_url": "https://api.github.com/users/pramit-marattha/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/pramit-marattha/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/pramit-marattha/subscriptions",
  "organizations_url": "https://api.github.com/users/pramit-marattha/orgs",
  "repos_url": "https://api.github.com/users/pramit-marattha/repos",
  "events_url": "https://api.github.com/users/pramit-marattha/events{/privacy}",
  "received_events_url": "https://api.github.com/users/pramit-marattha/received_events",
  "type": "User",
  "site_admin": false,
  "name": "pramitmarattha",
  "company": "@risk-first @x-47 ",
  "blog": "",
  "location": "Earth",
  "email": null,
  "hireable": true,
  "bio": "Python | Javascript\r\n    \r\n",
  "twitter_username": "pramit_armpit",
  "public_repos": 77,
  "public_gists": 0,
  "followers": 22,
  "following": 17,
  "created_at": "2018-03-22T07:08:40Z",
  "updated_at": "2020-07-20T18:11:33Z"
};